

services:
  postgres:
    image: postgres:18
    container_name: foodit-postgres

    environment:
      POSTGRES_DB: foodit
      POSTGRES_USER: foodit
      POSTGRES_PASSWORD: foodit_dev_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: